services:
  mongodb:
    image: devseiti/mongo-4
    command: [--auth]
    container_name: mongodb
    volumes: 
    - bd:/data/db
    networks:
      - rede
    ports:
      - 27018:27017

  frontend:
    image: cadudtechta/virtual:19-04
    command: >
      sh -c "npm install &&
             npm run startf"
    networks:
      - rede
    ports:
      - 8443:8443
      - 25700:25700
  
  backend:
    image: cadudtechta/virtual:27-03
    command: >
      sh -c "npm install &&
             npm run startb"
    networks:
      - rede
    ports:
      - 50000-50400:50000-50400

volumes:
  bd:
    external: true

networks:
  rede:
    driver: bridge
